### ISSUE TITLE
[Test request] Test numerical stability for SoftMax.jl

### ISSUE THREAD

**Issue by stevenygd** [stevenygd/NN.jl#19]
Need to include test for numerical stability for the layer SoftMax.jl.

**Comment by fufjvnvnf** [comment]
How big of the numbers are you expecting? I've tested with matrices with values in the range of + or - 501698601 and Softmax layers outputs all 0s, while ForwardDiff outputs NaNs.

**Comment by fufjvnvnf** [comment]
Something worth noting is that Julia's `exp` function itself is pretty imprecise, as shown in the picture below:
<img width="232" alt="2017-08-15 11 55 28" src="https://user-images.githubusercontent.com/20451799/29301733-e2513558-81b0-11e7-892e-6c19b639f22c.png">
It is thus unlikely for us to count on Julia calculating Softmax with number over few hundreds for us.

**Comment by fufjvnvnf** [comment]
A workaround could be achieved as this:
<img width="682" alt="2017-08-15 12 05 01" src="https://user-images.githubusercontent.com/20451799/29301941-826132b8-81b2-11e7-95bc-ebcf6a848326.png">
But the extra allocations required might be extremely wasteful in the usual case.

**Comment by stevenygd** [comment]
Seems like that's not some case we need to worry about so far. Close the issue for now.
