### ISSUE TITLE
Wrap Layer constants

### ISSUE THREAD

**Issue by Tiiiger** [stevenygd/NN.jl#25]
Create new Julia type to wrap four common layer field: parents, children, has_init, id.
Also, due to change in interface, has_init is unnecessary now. This field should be removed in the future.

**Comment by Tiiiger** [comment]
Finish Interface Change for Addition, Input, Dense, SoftMaxCrossEntropy. More to be changed after MNIST demo.

**Comment by fufjvnvnf** [comment]
Resolved.
